version: '3'

services:
  nginx-rtmp:
    build: .
    ports:
      - 1935:1935
      - 80:80
      - 443:443
    restart: always
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
      - HTTPS_PORT=443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
